---
- name: Verify
  hosts: all
  connection: local
  become: false
  gather_facts: false

  tasks:
    - import_tasks: tests/test_security_updates.yml
    - import_tasks: tests/test_cassandra_mqtt.yml
    - import_tasks: tests/test_wifi_led.yml
