---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload sysctl
  ansible.builtin.command:
    cmd: /sbin/sysctl --system

- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager.service
    state: restarted
