---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Reload sysctl
  ansible.builtin.command:
    cmd: /sbin/sysctl --system

- name: Restart NetworkManager
  ansible.builtin.systemd:
    name: NetworkManager.service
    state: restarted

- name: Restart systemd-journald
  ansible.builtin.systemd:
    name: systemd-journald.service
    state: restarted

- name: Restart cassandra
  ansible.builtin.systemd:
    name: cassandra.service
    state: restarted

- name: Restart wifi-led
  ansible.builtin.systemd:
    name: wifi-led.service
    state: restarted
    daemon_reload: true
